name: parichaya_frontend
description: Flutter project for mobile app of Parichaya.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  provider: ^6.0.2
  image_picker: ^0.8.4+6
  # transparent_image: ^2.0.0
  sqflite: ^2.0.2
  path_provider: ^2.0.8
  shared_preferences: ^2.0.13
  photo_view: ^0.12.0
  image_gallery_saver: ^1.7.1
  permission_handler: ^9.0.1
  connectivity_plus: ^2.2.1
  share_plus: ^3.0.5
  qr_flutter: ^4.0.0
  flutter_native_splash: ^2.0.5
  flutter_native_image: ^0.0.6+1
  uuid: ^3.0.6
  flutter_document_scanner: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#0F0F0F"
  image: assets/images/light-splash-logo.png
  image_dark: assets/images/dark-splash-logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand-Regular.ttf
